smoother_server:
  ros__parameters:
    use_sim_time: true
    smoother_plugins: ["simple_smoother"]
    
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-8
      max_its: 500
      do_refinement: true 
      
      w_data: 0.3 
      w_smooth: 0.2 
      
      refinement_ctr: 2 
      refinement_num: 2 