slam_toolbox:
  ros__parameters:
    use_sim_time: false

    # Frames
    map_frame: map
    odom_frame: odom
    base_frame: base_link

    # Mode
    mode: mapping

    # Laser
    scan_topic: scan
    max_laser_range: 12.0
    throttle_scans: 1

    # Map
    resolution: 0.05
    map_update_interval: 2.0

    # Motion thresholds
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2

    # TF
    transform_publish_period: 0.05

    # Loop closure
    do_loop_closing: true
    loop_closure_threshold: 11.0
    loop_closure_search_radius: 8.0

    # Solver
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_trust_strategy: LEVENBERG_MARQUARDT

    # Interactive
    enable_interactive_mode: true
